spring.application.name=appointments

spring.datasource.url=jdbc:mysql://localhost:3307/hospitaldb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=8f84106d5a5f025c3a894b4ab911f762852b481e6b082c90ada7887ede0f6f66
spring.jwt.expiration=900000
